spring:
  cloud:
    gateway:
      routes:
        - id: authorization-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth
          filters:
            - JwtAuthentication
        - id: users_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/users
          filters:
            - JwtAuthentication
        - id: refresh_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/refresh
          filters:
            - JwtAuthentication
        - id: take_users
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthentication
        - id: talk_with_duckduckgo
          uri: http://localhost:8082
          predicates:
            - Path=/ai/duckduckgo
          filters:
            - JwtAuthentication
        - id: history
          uri: http://localhost:8082
          predicates:
            - Path=/ai/history
          filters:
            - JwtAuthentication
        - id: update_user_info
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthentication
        - id: update_user_id
          uri: http://localhost:8082
          predicates:
            - Path=/api/chats/update-user-id
          filters:
            - JwtAuthentication




jwt:
  auth:
    requiredAuthorities:
      - user
      - admin

server:
  port: 8080

token:
  signing: #JWT TOKEN
